### ISSUE TITLE
Allow to modify margin of the keys

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/number-keyboard#11]

**Comment by RaghavendraDex** [comment]
after an update of constraint layout from 2.0.0-beta1 to 2.0.0-beta2 the Keyboard UI is getting left aligned by default.
![view](https://user-images.githubusercontent.com/52152316/62039008-7398e200-b214-11e9-8a8f-ad9a11ade433.png)

**Comment by davidmigloz** [comment]
Hi @RaghavendraDex 

Thanks for reporting. I've also experienced some issues with constraint layout `2.0.0-beta2`. Apparently is [less stable](https://www.reddit.com/r/androiddev/comments/c3g1n5/low_performance_in_constraintlayout_200beta2/) than `2.0.0-beta1`. I'm my production app where I use this library I'm still using `2.0.0-beta1`. Is it working fine if you use `2.0.0-beta1`?

**Comment by RaghavendraDex** [comment]
Yes it is working fine with 2.0.0-beta1

**Comment by davidmigloz** [comment]
Then I would stick to that one for now until they release a more stable version. I'll update the library to depend on that version then.

**Comment by MuzaffarAbduboqiyev** [comment]
How to restart password after set password

**Comment by davidmigloz** [comment]
this should be possible now with the compose version
