### ISSUE TITLE
Allow to set keys font size

### ISSUE THREAD

**Issue by saeed74** [davidmigloz/number-keyboard#15]
awesome library by the way.

**Comment by davidmigloz** [comment]
Hi @saeed74, thanks for reporting. There's already a ticket about the margin between keys #11. Regarding the size, the library is using Autosizing TextViews, so the text adapts its size based on the key size. Maybe I can expose `autoSizeMinTextSize` and `autoSizeMaxTextSize`. About the font I agree, I'll add that functionality.

**Comment by davidmigloz** [comment]
I'll leave this ticket for the font size feature and create a new one for the font type. Thanks.

**Comment by alonfi** [comment]
Hi @davidmigloz, any news on this issue?

**Comment by davidmigloz** [comment]
Unfortunately not, I didn't have time to work on it yet.

**Comment by davidmigloz** [comment]
This should be possible now with the compose version
