### ISSUE TITLE
Allow to set keys font type

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/number-keyboard#17]

**Comment by gerywahyunugraha** [comment]
Hi @davidmigloz, I've created a merge request to add this feature, can you check it?
Thanks!

**Comment by davidmigloz** [comment]
@gerynugrh sorry I totally missed your PR from 3 years ago (I haven't been maintaining the library very actively)

The new migration to compose should allow to set the font type as well, so I'll close this issue.
