### ISSUE TITLE
Resource Error

### ISSUE THREAD

**Issue by milindrc** [davidmigloz/number-keyboard#19]
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png from drawable resource ID #0x7f0700fd: .xml extension required

**Comment by davidmigloz** [comment]
Hi Milindrc,
Can you give more details about how to reproduce the issue? 
Thanks!

**Comment by milindrc** [comment]
It was resolved when I downloaded and imported it.

On 23-Oct-2018 10:32 PM, David Miguel Lozano <notifications@github.com> wrote:

Hi Milindrc,
Can you give more details about how to reproduce the issue?
Thanks!

**Comment by davidmigloz** [comment]
Perfect! I'll close the issue then.

**Comment by sgt2350** [comment]
Hey Please give the link where you downloaded it from ?

**Comment by milindrc** [comment]
download it from sample of this repo
