### ISSUE TITLE
Keyboard view not opening

### ISSUE THREAD

**Issue by GajanandSwamy** [davidmigloz/number-keyboard#3]
After pressing  buttons in main activity. particular keyboard is not opening.

only text 0 is showing no keyboard.

**Comment by davidmigloz** [comment]
Hi @GajanandSwamy,

Can you describe a bit more the issue?
Which main activity do you mean?

Thanks for your help.

**Comment by naveeng915213** [comment]
HI davidmigloz,

I can't see a keypad buttons other than zero.  After clicking the openKeyboardInteger button from main activity. Can you help me out?

**Comment by davidmigloz** [comment]
Hi naveeng915213,

Can you show me how you are using the library?
I need some more info/code. 

Thanks.

**Comment by GajanandSwamy** [comment]
Even i got the same issue. David please run your code on Android M and above.

Thanks

**Comment by naveeng915213** [comment]
Hi davidmigloz,

I copied the lib classes and dependencies and tested, Its only showing textview "0"
not keypad.

Thanks.

**Comment by davidmigloz** [comment]
You don't need to copy the lib classes, you can import the library from your `build.gradle` file:

```
compile 'com.github.davidmigloz:number-keyboard:1.0'
```

Again, if you show me a piece of code I could help you. You can also check the [sample app](https://github.com/davidmigloz/number-keyboard/tree/master/sample).

**Comment by davidmigloz** [comment]
I'll close the issue. If you are still experiencing it, please reopen it providing further details.
