### ISSUE TITLE
can not resolve.

### ISSUE THREAD

**Issue by GuruKarmakar** [davidmigloz/number-keyboard#5]

**Comment by davidmigloz** [comment]
Hi, can you give some more details? 
I don't get any problem resolving the library.
You can check it in JitPack https://jitpack.io/#davidmigloz/number-keyboard

**Comment by GuruKarmakar** [comment]
sorry, it was my mistake....i forget to add maven{}..
thanks..

**Comment by davidmigloz** [comment]
No problem ;)
