### ISSUE TITLE
I would like to avoid to user to put comma...?

### ISSUE THREAD

**Issue by GuruKarmakar** [davidmigloz/number-keyboard#6]

**Comment by davidmigloz** [comment]
The library provides two auxiliary buttons (`leftAuxBtn` and `rightAuxBtn`) that you can configure to be whatever you need (comma, dot, fingerprint icon...). The library does not handle the logic of this two button, it just provides you two callbacks (`onLeftAuxButtonClicked()` and `onRightAuxButtonClicked()`) invoked when any of these buttons is pressed.
